semestrovka_django_2k/cart/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^cart/$', 'cart.views.cart', name='cart'),
                       url(r'^del_from_cart/(?P<id>\d+)/$', 'cart.views.del_from_cart', name='del'),
                       url(r'^order/$', 'cart.views.order', name='order'),
                       url(r'^add_to_cart/(?P<id>\d+)/$', 'cart.views.add_to_cart', name='add_to_cart')
                       )

semestrovka_django_2k/catalog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^categories/(?P<id>\d+)/$', 'catalog.views.one_category', name='by_category'),
                       url(r'^product/(?P<id>\d+)/$', 'catalog.views.product', name='product'),
                       url(r"^products/add_like/(?P<id>\d+)/$", 'catalog.views.add_like_product',
                           name='add_like_product'),
                       url(r'^add_comment/(?P<id>\d+)/$', 'catalog.views.add_comment', name='add_comment'),
                       url(r'^del_comment/(?P<id>\d+)/$', 'catalog.views.del_comment', name='del_comment'),
                       url(r'^search/$', 'catalog.views.search', name='search'),
                       )

semestrovka_django_2k/semestrovka_django_2k/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import settings

urlpatterns = [
    url(r'^admin', include(admin.site.urls)),
    url(r'^auth/', include('client.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_URL}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('goldenshop.urls', namespace="goldenshop")),
    url(r'^', include('catalog.urls', namespace="catalog")),
    url(r'^', include('cart.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
]

semestrovka_django_2k/cart/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from catalog.models import Product

payment = (('in cash', 'in cash'),
           ('credit card', 'credit card'))

shipping = (('Russian POST', 'Russian POST'), ('SPSR', 'SPSR'))


class Cart(models.Model):
    class Meta:
        db_table = "cart"

    owner = models.ForeignKey(User)
    product = models.ForeignKey(Product, null=True, default=None)
    quantity = models.PositiveIntegerField(null=True, validators=[MinValueValidator(1)])


class Shipping(models.Model):
    shipping_method = models.CharField(max_length=50, choices=shipping, verbose_name="Shipping Method", blank=True,
                                       null=True)
    shipping_price = models.FloatField("Shipping Price", default=0.0)
    shipping_tax = models.FloatField("Shipping Tax", default=0.0)


class Payment(models.Model):
    payment_method = models.CharField(max_length=50, choices=payment, verbose_name="Payment Method", blank=True,
                                      null=True)
    payment_price = models.FloatField("Payment Price", default=0.0)
    payment_tax = models.FloatField("Payment Tax", default=0.0)


class CreditCard(models.Model):
    number = models.CharField("Number", blank=True, max_length=30)
    bank_name = models.CharField("Bank name", blank=True, max_length=100)
    expiration_date_month = models.IntegerField("Expiration date month", blank=True, null=True)
    expiration_date_year = models.IntegerField("Expiration date year", blank=True, null=True)


class Address(models.Model):
    firstname = models.CharField("Firstname", max_length=50, blank=False)
    lastname = models.CharField("Lastname", max_length=50, blank=False)
    zip_code = models.CharField("Zip code", max_length=10, blank=False)
    city = models.CharField("City", max_length=50, blank=False)
    state = models.CharField("State", max_length=50, blank=True, null=True)
    country = models.CharField("Country", max_length=30, blank=True, null=True)

semestrovka_django_2k/catalog/models.py
from django.db import models
from datetime import *
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        db_table = "category"
        ordering = ['category_title']

    def __str__(self):
        return self.category_title

    category_title = models.CharField(max_length=30)

    def get_absolute_url(self):
        return "/categories/%i/" % self.id


class Product(models.Model):
    class Meta:
        db_table = "products"
        verbose_name_plural = 'Products'
        unique_together = ['product_title', 'product_short_description']

    product_category = models.ForeignKey(Category)
    product_title = models.CharField(max_length=20)
    product_short_description = models.TextField()
    product_img = models.ImageField(upload_to="images")
    product_cost = models.PositiveIntegerField(default=0)
    release_date = models.DateTimeField(default=datetime.now)
    likes = models.IntegerField(default=0)
    available = models.BooleanField()

    def is_available(self):
        if self.available:
            return 'Exists'
        else:
            return 'Not exist'

    def __str__(self):
        return self.product_title

    def get_absolute_url(self):
        return "/product/%i/" % self.id


class Comment(models.Model):
    class Meta:
        db_table = "comments"
        ordering = ['comment_date']

    def __str__(self):
        return self.comment_text

    comment_text = models.TextField(help_text="Leave a comment")
    comment_date = models.DateTimeField(default=datetime.now)
    comment_product = models.ForeignKey(Product)
    comment_author = models.ForeignKey(User)

semestrovka_django_2k/cart/forms.py
from django.forms import ModelForm

from cart.models import *
from catalog.models import Comment
from client.models import UserProfile


class CartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['quantity']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']


class OrderForm(ModelForm):
    class Meta:
        model = UserProfile
        # Shipping, Payment, CreditCard, Address
        fields = ['email']
        #  'shipping_method', 'shipping_price',
        # 'shipping_tax', 'payment_method', 'payment_price', 'payment_tax',
        # 'number', 'bank_name', 'expiration_date_month', 'expiration_date_year',
        # 'firstname', 'lastname', 'zip_code', 'city', 'state', 'country']

semestrovka_django_2k/catalog/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

semestrovka_django_2k/cart/views.py
from catalog.models import *
from cart.models import *
from client.models import User
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.core.context_processors import csrf
from cart.forms import CartForm, OrderForm


def add_to_cart(request, id):
    product_id = id
    if request.POST:
        username = request.user.id
        if username is not None:
            form = CartForm(request.POST)
            if form.is_valid():
                cart = form.save(commit=False)
                cart.owner = User.objects.get(id=request.user.id)
                cart.product = Product.objects.get(id=id)
                form.save()
                return redirect('/cart')
    return redirect('/product/%s/' % product_id)


def cart(request):
    username = request.user.id
    args = {'categories': Category.objects.all()}
    if username is not None:
        args['username'] = auth.get_user(request).username
        args['email'] = OrderForm
        args.update(csrf(request))
        args['cart'] = Cart.objects.filter(owner=username).raw(
            'SELECT cart.id,product_title, products.product_cost AS cost,quantity*products.product_cost '
            'AS price,quantity,product_id FROM cart, products WHERE cart.product_id=products.id ')
        return render_to_response('cart.html', args)
    else:
        return redirect('/auth/login/')


def order(request):
    if request.POST:
        form = OrderForm(request.POST)
        if form.is_valid():
            for object in Cart.objects.all():
                object.delete()
            return redirect('/')
        else:
            return redirect('/cart/')


def del_from_cart(request, id):
    Cart.objects.get(id=id).delete()
    return redirect('/cart/')

semestrovka_django_2k/catalog/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy

from catalog.models import *
from cart.models import *
from client.models import *
from django.shortcuts import *
from django.contrib import auth
from django.core.context_processors import csrf
from cart.forms import CartForm
from catalog.forms import CommentForm


def one_category(request, id):
    args = {'category': Category.objects.filter(id=id), 'products': Product.objects.filter(product_category=id),
            'categories': Category.objects.all()}
    print(Category.objects.filter(id=id))
    username = request.user.id
    if username is not None:
        args['username'] = auth.get_user(request).username
    return render_to_response('catalog.html', args)


def product(request, id):
    username = request.user.id
    comment_form = CommentForm
    cart_form = CartForm
    args = {'comments': Comment.objects.filter(comment_product_id=id),
            'form': comment_form,
            'cart_add_form': cart_form,
            'product': Product.objects.get(id=id),
            'categories': Category.objects.all(),
            'other_products': Product.objects.exclude(id=id).order_by('product_category')[:5],
            }
    args.update(csrf(request))
    if username is not None:
        args['username'] = auth.get_user(request).username
    return render_to_response('product.html', args)


# ПОДПРАВИТЬ
@login_required(login_url=reverse_lazy("login"))
def add_like_product(request, id):
    username = auth.get_user(request).username
    q = username + "_" + id
    try:
        product_id = id
        x = Product.objects.get(id=product_id)
        if q in request.COOKIES:
            f = Product.objects.get(id=product_id)
            return HttpResponse(f.likes)
        else:
            f = Product.objects.get(id=product_id)
            http_response = HttpResponse(f.likes)
            http_response.set_cookie(q, "likes product %s" % product_id)
            f = Product.objects.get(id=product_id)
            f.likes += 1
            f.save()
            # response = redirect('/product/%s/' % x.id)
            # response.set_cookie(q, "likes product %s" % product_id)
            return HttpResponse(f.likes)
    except ObjectDoesNotExist:
        raise Http404
    return redirect('/product/%s/' % x.id)


def add_comment(request, id):
    product_id = id
    if request.POST and ('pause' not in request.session):
        c = Comment()
        c.comment_product = Product.objects.get(id=product_id)
        c.comment_author = User.objects.get(id=request.user.id)
        c.comment_text = request.POST['comment']
        c.save()
        # form = CommentForm(request.POST)
        # if form.is_valid():
        #     comment = form.save(commit=False)
        #     comment.comment_product = Product.objects.get(id=product_id)
        #     comment.comment_author = User.objects.get(id=request.user.id)
        #     form.save()
        #     request.session.set_expiry(30)
            # request.session['pause'] = True
    return redirect('/product/%s/' % product_id)


def del_comment(request, id):
    Comment.objects.get(id=id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def search(request):
    args = {}
    if ('search' in request.GET) and (request.GET['search']):
        s = request.GET['search']
        result = Product.objects.filter(product_title__contains=s)
        args['products'] = result
        args['categories'] = Category.objects.all()
        return render_to_response('catalog.html', args)
    else:
        args['search'] = 'Nothing found'
        args['categories'] = Category.objects.all()
        return render_to_response('catalog.html', args)

semestrovka_django_2k/catalog/templates/cart.html
{% extends 'index.html' %}
{% block cart %}
    <div class="row">
        <table class="simple-little-table" cellspacing='0'>
            <tr>
                <th>Cart</th>
            </tr>
            <tr>
                <td>Title</td>
                <td>Quantity</td>
                <td>Cost</td>
                <td>Price</td>
                <td>Delete?</td>
            </tr>
            {% for row in cart %}
                <tr>
                    <td><a href="{% url 'catalog:product' row.product_id %}">{{ row.product }}</a></td>
                    <td>{{ row.quantity }}</td>
                    <td>{{ row.cost }}</td>
                    <td>{{ row.price }}</td>
                    <td><a href="{% url 'del' row.id %}">X</a></td>
                </tr>
            {% endfor %}
        </table>
        <div class="center">
            <form method="POST" action="{% url 'order' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="small-8 columns">
                        <div class="row">
                            <div class="small-3 columns">
                                <label for="right-label" class="right inline">{{ email.label }}</label>
                            </div>
                            <div class="small-9 columns">
                                {{ email }}
                                <input class="button postfix" type="submit" value="Order">
                            </div>
                        </div>
                    </div>

                </div>

            </form>
        </div>
    </div>
{% endblock %}

semestrovka_django_2k/catalog/templates/catalog.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load imagekit %}
{% block catalog %}
    <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
        <ul class="orbit-container" style="height: 429px;">
            <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;
            </button>
            <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
            <li class="orbit-slide is-active">
                <a href="#1">
                    <img src="{% static 'images/logo.jpeg' %}" height="150" width="1910">
                </a>
            </li>
        </ul>
    </div>
    <div class="row column text-center">
        {% if category %}
            <h2 id="1">In this category:</h2>
            <hr>
        {% else %}
            <h2 id="1">Our Newest Products</h2>
            <hr>
        {% endif %}

    </div>
    <div class="row small-up-2 large-up-4">
        {% for product in newest_products %}
            <div class="column">
                {% thumbnail '300x300' product.product_img -- class="thumbnail"%}
                <h5>{{ product.product_title }}</h5>
                <p>{{ product.product_cost }} $</p>
                <a href="{{ product.get_absolute_url }}" class="button expanded">More</a>
            </div>
        {% endfor %}
    </div>
    {% if not category %}
        <hr>
        <div class="row column text-center">
            <h2>Some Other Cheap Products</h2>
            <hr>
        </div>
        <div class="row small-up-2 medium-up-3 large-up-6">
            {% for product in cheap_products %}
                <div class="column">
                    {% thumbnail '300x300' product.product_img -- class="thumbnail"%}
                    <h5>{{ product.product_title }}</h5>
                    <p>{{ product.product_cost }} $</p>
                    <a href="{{ product.get_absolute_url }}" class="button expanded">More</a>
                </div>
            {% endfor %}
        </div>
        <hr>
    {% endif %}
    <div class="row">
        <h4>All Products</h4>
        {% for product in products %}
            <div class="medium-4 columns">
                <div class="media-object">
                    <div class="media-object-section">
                        {% thumbnail '100x100' product.product_img -- class="thumbnail" %}
                    </div>
                    <div class="media-object-section">
                        <h5>{{ product.product_title }}</h5>
                        <p>{{ product.product_cost }}$</p>
                        <a href="{{ product.get_absolute_url }}" class="button expanded">More</a>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
    <center>
        {% if not category %}
            <div class="pagination-centered">
                <ul class="pagination">
                    {% if products.has_previous %}
                        <li class="arrow"><a href="/page/{{ albums.previous_page_number }}/">&laquo;</a></li>
                    {% else %}
                        <li class="arrow unavailable"><a href="">&laquo;</a></li>
                    {% endif %}
                    {% for page in products.paginator.page_range %}
                        {% if page == products.number %}
                            <li class="current"><a href="/page/{{ page }}/">{{ page }}</a></li>
                        {% else %}
                            <li><a href="/page/{{ page }}/">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if products.has_next %}
                        <li class="arrow"><a href="/page/{{ albums.next_page_number }}/">&raquo;</a></li>
                    {% else %}
                        <li class="arrow unavailable"><a href="">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </center>
{% endblock %}

semestrovka_django_2k/catalog/templates/product.html
{% extends 'index.html' %}
{% block one_product %}
    {% load imagekit %}
    {% load staticfiles %}
    <html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script>
            $(function () {
                $('#likes').click(function () {
                    $.get('/products/add_like/{{ product.id }}', function (data) {
                        $('#like_count').html(data);
                    });
                });
            });
        </script>
        <script type='text/javascript'>
            function countChar(val) {
                var len = val.value.length;
                var text_max = 200;

                if (len >= text_max) {
                    val.value = val.value.substring(0, text_max);
                    $('#textarea_feedback').text((text_max - len));
                } else {
                    $('#textarea_feedback').text((text_max - len));
                }
            }
        </script>
    </head>
    <body>
    <br>
    <div class="row columns">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="/">Home</a></li>
                <li><a href="/categories/{{ product.product_category.id }}/">{{ product.product_category }}</a></li>
                <li>
                    <span class="show-for-sr">Current: </span> {{ product.product_title }}
                </li>
            </ul>
        </nav>
    </div>

    <div class="row">
        <div class="medium-6 columns">
            {% thumbnail '300x300' product.product_img -- class="thumbnail" %}
        </div>
        <div class="medium-6 large-5 columns">
            <h3>{{ product.product_title }}</h3>
            <p> {{ product.product_short_discription }}</p>
            <p>{{ product.product_distributor }}</p>
            <p>{{ product.product_cost }}$</p>
            {% if username %}
                <button id="likes"><img
                        src="{% static "images/like.jpg" %} " type="button" alt="Like"
                        width="25px" height="25px">
                    <span id="like_count"> {{ product.likes }} </span>
                </button>
            {% endif %}
            {% if product.available %}
                {% if username %}
                    <form action="{% url 'add_to_cart' product.id %}" method="POST">
                        <div class="row">
                            <div class="small-3 columns">
                                <label for="middle-label" class="middle">Quantity</label>
                            </div>
                            {% csrf_token %}
                            <div class="small-9 columns">
                                {{ cart_add_form.quantity }}
                            </div>
                        </div>
                        <input type="submit" class="button large expanded" value="Add to cart">
                    </form>
                {% else %}
                    <H5>Please, log in to add this item to your cart</H5>
                {% endif %}
            {% else %}
                <p>Not available :(</p>
                <p>Please check back later</p>
            {% endif %}
        </div>
    </div>
    <div class="column row">
        <hr>
        <ul class="tabs" data-tabs id="example-tabs">
            <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Comments</a></li>
            <li class="tabs-title"><a href="#panel2">Similar Products</a></li>
        </ul>
        <div class="tabs-content" data-tabs-content="example-tabs">
            <div class="tabs-panel is-active" id="panel1">
                <h4>Comments</h4>
                {% for comment in comments %}
                    <div class="media-object stack-for-small">
                        <div class="media-object-section">
                            {#                            <img src="{{ profile.avatar.url }}" width="300" height="300">#}
                        </div>
                        <div class="media-object-section">
                            <h5> {{ comment.comment_author }}</h5>
                            <p>{{ comment.comment_text }}
                                {% ifequal comment.comment_author|stringformat:"s" username %}
                                    <a href="{% url 'catalog:del_comment' comment.id %}">Delete</a>
                                {% endifequal %}
                            </p>
                            <p class="help-block">{{ comment.comment_date }}</p>
                        </div>
                    </div>
                {% endfor %}
                {% if username %}
                    <div id="textarea_feedback">140</div>
                    <form method="post" action="{% url 'catalog:add_comment' product.id %}">
                        <textarea name="comment" id="textarea" maxlength="140" onkeyup="countChar(this)"></textarea>
                        {% csrf_token %}
                        <input type="submit">
                    </form>
                {% endif %}
            </div>

            <div class="tabs-panel " id="panel2">
                <div class="row medium-up-3 large-up-5">

                    {% for other_product in other_products %}
                        <div class="column">
                            {% thumbnail '350x350' other_product.product_img -- class="thumbnail" %}
                            <h5>{{ other_product.product_title }}
                                <small><br>{{ other_product.product_cost }} $</small>
                            </h5>
                            <p>{{ other_product.product_short_discription }}</p>
                            <a href="{{ other_product.get_absolute_url }}" class="button hollow tiny expanded">See
                                more</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}


</body>
</html>