semestrovka_django_2k/cart/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^cart/$', 'cart.views.cart', name='cart'),
                       url(r'^del_from_cart/(?P<id>\d+)/$', 'cart.views.del_from_cart', name='del'),
                       url(r'^order/$', 'cart.views.order', name='order'),
                       url(r'^add_to_cart/(?P<id>\d+)/$', 'cart.views.add_to_cart', name='add_to_cart')
                       )

semestrovka_django_2k/catalog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^categories/(?P<id>\d+)/$', 'catalog.views.one_category', name='by_category'),
                       url(r'^product/(?P<id>\d+)/$', 'catalog.views.product', name='product'),
                       url(r"^products/add_like/(?P<id>\d+)/$", 'catalog.views.add_like_product',
                           name='add_like_product'),
                       url(r'^add_comment/(?P<id>\d+)/$', 'catalog.views.add_comment', name='add_comment'),
                       url(r'^del_comment/(?P<id>\d+)/$', 'catalog.views.del_comment', name='del_comment'),
                       url(r'^search/$', 'catalog.views.search', name='search'),
                       )

semestrovka_django_2k/goldenshop/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('',
                       url(r'^$', 'goldenshop.views.index'),
                       url(r"^page/(\d+)/$", 'goldenshop.views.index'),
                       url(r'^about', 'goldenshop.views.about', name='about'),
                       url(r'^contact', 'goldenshop.views.contact', name='contact'),
                       url(r'^reviews', 'goldenshop.views.review', name='reviews'),
                       url(r'^add_reviews', 'goldenshop.views.add_review', name='add_reviews')
                       )

semestrovka_django_2k/semestrovka_django_2k/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import settings

urlpatterns = [
    url(r'^admin', include(admin.site.urls)),
    url(r'^auth/', include('client.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_URL}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('goldenshop.urls', namespace="goldenshop")),
    url(r'^', include('catalog.urls', namespace="catalog")),
    url(r'^', include('cart.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
]

semestrovka_django_2k/goldenshop/models.py
from django.contrib.auth.models import User
from datetime import *
from django.db import models


class Review(models.Model):
    class Meta:
        db_table = "reviews"
        ordering = ['review_date']

    def __str__(self):
        return self.review_text

    review_text = models.TextField(help_text="Leave a comment")
    review_date = models.DateTimeField(default=datetime.now)
    review_author = models.ForeignKey(User)

semestrovka_django_2k/goldenshop/forms.py
from django.forms import ModelForm

from goldenshop.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['review_text']

semestrovka_django_2k/goldenshop/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.template.context_processors import csrf

from catalog.models import Product, Category
from client.models import UserProfile
from goldenshop.forms import ReviewForm
from goldenshop.models import *


def index(request, page_number=1):
    all_products = Product.objects.all()
    current_page = Paginator(all_products, 9)
    args = {'products': current_page.page(page_number),
            'categories': Category.objects.all(),
            'newest_products': Product.objects.all().order_by('-release_date')[:4],
            'cheap_products': Product.objects.all().order_by('product_cost')[:6]}
    username = request.user.id
    if username is not None:
        args['username'] = auth.get_user(request).username
    return render_to_response('catalog.html', args)


def review(request):
    profile = UserProfile.objects.get(user=request.user)
    review_form = ReviewForm
    args = {'reviews': Review.objects.all(),
            'form': review_form,
            'profile': profile}
    args.update(csrf(request))
    return render_to_response('Reviews.html', args)


def about(request):
    return render_to_response('About.html')


def contact(request):
    return render_to_response('Contact.html')


def add_review(request):
    form = ReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.review_author = User.objects.get(id=request.user.id)
        form.save()
        request.session.set_expiry(30)
        # request.session['pause'] = True
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

semestrovka_django_2k/goldenshop/templates/About.html
{% extends 'index.html' %}
{% block about %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div style="padding: 20%">
    <H1>Discover</H1> <span>the best products on Golden shop, curated by Golden Amir with great taste.
Golden shop features beautiful and functional products, you can actually buy. We bring boutique curation to the Internet’s largest catalog.</span>
</div>
</body>
</html>
{% endblock %}

semestrovka_django_2k/goldenshop/templates/Contact.html
{% extends 'index.html' %}
{% block contacts %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="padding: 20%">
    <H1>Директор: Галимуллин Амир Рамильевич</H1>
    <H2>8-937-777-37-29</H2>
    <H3>amirzolotoy@gmail.com</H3>
    </div>
</body>
</html>
{% endblock %}

semestrovka_django_2k/goldenshop/templates/Reviews.html
{% extends 'index.html' %}
{% block reviews %}
<div class="tabs-content" data-tabs-content="example-tabs">
    <div class="tabs-panel is-active" id="panel1">
        <h4>Reviews:</h4>
        {% for review in reviews %}
            <div class="media-object stack-for-small">
                <div class="media-object-section">
                    <h5> {{ review.review_author }}</h5>
                    <p>{{ review.review_text }}
{#                                                        {% ifequal review.review_author|stringformat:"s" username %}#}
{#                                                            <a href="{% url 'catalog:del_comment' review.id %}">Delete</a>#}
{#                                                        {% endifequal %}#}
                    </p>
                    <p class="help-block">{{ review.review_date }}</p>
                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{% url 'goldenshop:add_reviews' %}" method="POST">
                {{ form }}{% csrf_token %}
                <input type="submit" class="button" value="Add review">
            </form>
        </div>
    </div>
</div>
{% endblock %}